name: requests
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  meta: ^1.7.0

dev_dependencies:
  json_serializable: ^4.1.3
  json_annotation: ^4.0.1
  build_runner: ^2.0.6
  pedantic: ^1.10.0
  test: ^1.16.0
  logging: any
