name: requests
description: A starting point for Dart libraries or applications.
version: 1.0.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  logging: ^1.0.1
  meta: ^1.3.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
